### ISSUE TITLE
Support for Custom Ranges

### ISSUE THREAD

**Issue by iv4n-ga6l** [raphoester/chaos#2]
Allow users to specify custom ranges for the Int, Float, and Duration functions instead of always starting at 0.

- IntRange(min, max int, seed ...any) int
- FloatRange(min, max float64, seed ...any) float64
- DurationRange(min, max time.Duration, seed ...any) time.Duration

**Comment by raphoester** [comment]
Was on the backlog, feel free to submit a PR 
Although the naming is not very clear, prefer `IntInRange` or `RangeInt` to represent that we are generating an int in the range, not an int range

**Comment by iv4n-ga6l** [comment]
I just submitted a PR for this issue
https://github.com/raphoester/chaos/pull/4
